run:
  timeout: 5m

linters:
  enable:
    - goimports 
    - gofumpt
    - govet
    - staticcheck
    - gosimple
    - errcheck
    - ineffassign
    - unused
    - bodyclose
    - gosec

issues:
  exclude-use-default: false
